package dominik.majap.Anglictina;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;
import android.widget.SimpleAdapter;
import dominik.majap.R;
import java.util.ArrayList;
import java.util.HashMap;

public class nepravidelna_slovesa extends AppCompatActivity {
    ListView listView;

    /* access modifiers changed from: protected */
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView((int) R.layout.activity_nepravidelna_slovesa);
        setRequestedOrientation(1);
        setTitle("Nepravidelná slovesa");
        this.listView = (ListView) findViewById(R.id.listView_aj);
        ArrayList<HashMap<String, String>> list = new ArrayList<>();
        new HashMap();
        HashMap hashmap = new HashMap();
        hashmap.put("slovo_cesky", "být");
        hashmap.put("prvni_tvar", "be");
        hashmap.put("druhy_tvar", "was, were");
        hashmap.put("treti_tvar", "been");
        list.add(hashmap);
        HashMap hashmap2 = new HashMap();
        hashmap2.put("slovo_cesky", "tlouct");
        hashmap2.put("prvni_tvar", "beat");
        hashmap2.put("druhy_tvar", "beat");
        hashmap2.put("treti_tvar", "beaten");
        list.add(hashmap2);
        HashMap hashmap3 = new HashMap();
        hashmap3.put("slovo_cesky", "stát se");
        hashmap3.put("prvni_tvar", "become");
        hashmap3.put("druhy_tvar", "became");
        hashmap3.put("treti_tvar", "become");
        list.add(hashmap3);
        HashMap hashmap4 = new HashMap();
        hashmap4.put("slovo_cesky", "začít, začínat");
        hashmap4.put("prvni_tvar", "begin");
        hashmap4.put("druhy_tvar", "began");
        hashmap4.put("treti_tvar", "begun");
        list.add(hashmap4);
        HashMap hashmap5 = new HashMap();
        hashmap5.put("slovo_cesky", "kousnout,kousat");
        hashmap5.put("prvni_tvar", "bite");
        hashmap5.put("druhy_tvar", "bit");
        hashmap5.put("treti_tvar", "bitten");
        list.add(hashmap5);
        HashMap hashmap6 = new HashMap();
        hashmap6.put("slovo_cesky", "foukat,vanout");
        hashmap6.put("prvni_tvar", "blow");
        hashmap6.put("druhy_tvar", "blew");
        hashmap6.put("treti_tvar", "blown");
        list.add(hashmap6);
        HashMap hashmap7 = new HashMap();
        hashmap7.put("slovo_cesky", "rozbít");
        hashmap7.put("prvni_tvar", "break");
        hashmap7.put("druhy_tvar", "broke");
        hashmap7.put("treti_tvar", "broken");
        list.add(hashmap7);
        HashMap hashmap8 = new HashMap();
        hashmap8.put("slovo_cesky", "přinést, přivést");
        hashmap8.put("prvni_tvar", "bring");
        hashmap8.put("druhy_tvar", "brought");
        hashmap8.put("treti_tvar", "brought");
        list.add(hashmap8);
        HashMap hashmap9 = new HashMap();
        hashmap9.put("slovo_cesky", "stavět, postavit");
        hashmap9.put("prvni_tvar", "build");
        hashmap9.put("druhy_tvar", "built");
        hashmap9.put("treti_tvar", "built");
        list.add(hashmap9);
        HashMap hashmap10 = new HashMap();
        hashmap10.put("slovo_cesky", "hořet, spálit");
        hashmap10.put("prvni_tvar", "burn");
        hashmap10.put("druhy_tvar", "burned, burnt");
        hashmap10.put("treti_tvar", "burned, burnt");
        list.add(hashmap10);
        HashMap hashmap11 = new HashMap();
        hashmap11.put("slovo_cesky", "koupit, kupovat");
        hashmap11.put("prvni_tvar", "buy");
        hashmap11.put("druhy_tvar", "bought");
        hashmap11.put("treti_tvar", "bought");
        list.add(hashmap11);
        HashMap hashmap12 = new HashMap();
        hashmap12.put("slovo_cesky", "umět, moci");
        hashmap12.put("prvni_tvar", "can");
        hashmap12.put("druhy_tvar", "could");
        hashmap12.put("treti_tvar", "-");
        list.add(hashmap12);
        HashMap hashmap13 = new HashMap();
        hashmap13.put("slovo_cesky", "chytit, chytat");
        hashmap13.put("prvni_tvar", "catch");
        hashmap13.put("druhy_tvar", "caught");
        hashmap13.put("treti_tvar", "caught");
        list.add(hashmap13);
        HashMap hashmap14 = new HashMap();
        hashmap14.put("slovo_cesky", "přijít");
        hashmap14.put("prvni_tvar", "come");
        hashmap14.put("druhy_tvar", "came");
        hashmap14.put("treti_tvar", "come");
        list.add(hashmap14);
        HashMap hashmap15 = new HashMap();
        hashmap15.put("slovo_cesky", "stát (cena)");
        hashmap15.put("prvni_tvar", "cost");
        hashmap15.put("druhy_tvar", "cost");
        hashmap15.put("treti_tvar", "cost");
        list.add(hashmap15);
        HashMap hashmap16 = new HashMap();
        hashmap16.put("slovo_cesky", "řezat, krájet");
        hashmap16.put("prvni_tvar", "cut");
        hashmap16.put("druhy_tvar", "cut");
        hashmap16.put("treti_tvar", "cut");
        list.add(hashmap16);
        HashMap hashmap17 = new HashMap();
        hashmap17.put("slovo_cesky", "kopat (do země)");
        hashmap17.put("prvni_tvar", "dig");
        hashmap17.put("druhy_tvar", "dug");
        hashmap17.put("treti_tvar", "dug");
        list.add(hashmap17);
        HashMap hashmap18 = new HashMap();
        hashmap18.put("slovo_cesky", "dělat");
        hashmap18.put("prvni_tvar", "do");
        hashmap18.put("druhy_tvar", "did");
        hashmap18.put("treti_tvar", "done");
        list.add(hashmap18);
        HashMap hashmap19 = new HashMap();
        hashmap19.put("slovo_cesky", "kreslit");
        hashmap19.put("prvni_tvar", "draw");
        hashmap19.put("druhy_tvar", "drew");
        hashmap19.put("treti_tvar", "drawn");
        list.add(hashmap19);
        HashMap hashmap20 = new HashMap();
        hashmap20.put("slovo_cesky", "snít, mít sny");
        hashmap20.put("prvni_tvar", "dream");
        hashmap20.put("druhy_tvar", "dreamed, dreamt");
        hashmap20.put("treti_tvar", "dreamed, dreamt");
        list.add(hashmap20);
        HashMap hashmap21 = new HashMap();
        hashmap21.put("slovo_cesky", "pít");
        hashmap21.put("prvni_tvar", "drink");
        hashmap21.put("druhy_tvar", "drank");
        hashmap21.put("treti_tvar", "drunk");
        list.add(hashmap21);
        HashMap hashmap22 = new HashMap();
        hashmap22.put("slovo_cesky", "řídit, jet autem");
        hashmap22.put("prvni_tvar", "drive");
        hashmap22.put("druhy_tvar", "drove");
        hashmap22.put("treti_tvar", "driven");
        list.add(hashmap22);
        HashMap hashmap23 = new HashMap();
        hashmap23.put("slovo_cesky", "jíst");
        hashmap23.put("prvni_tvar", "eat");
        hashmap23.put("druhy_tvar", "ate");
        hashmap23.put("treti_tvar", "eaten");
        list.add(hashmap23);
        HashMap hashmap24 = new HashMap();
        hashmap24.put("slovo_cesky", "spadnout, padat");
        hashmap24.put("prvni_tvar", "fall");
        hashmap24.put("druhy_tvar", "fell");
        hashmap24.put("treti_tvar", "fallen");
        list.add(hashmap24);
        HashMap hashmap25 = new HashMap();
        hashmap25.put("slovo_cesky", "cítit, cítit se");
        hashmap25.put("prvni_tvar", "feel");
        hashmap25.put("druhy_tvar", "felt");
        hashmap25.put("treti_tvar", "felt");
        list.add(hashmap25);
        HashMap hashmap26 = new HashMap();
        hashmap26.put("slovo_cesky", "bojovat, prát se");
        hashmap26.put("prvni_tvar", "fight");
        hashmap26.put("druhy_tvar", "fought");
        hashmap26.put("treti_tvar", "fought");
        list.add(hashmap26);
        HashMap hashmap27 = new HashMap();
        hashmap27.put("slovo_cesky", "najít");
        hashmap27.put("prvni_tvar", "find");
        hashmap27.put("druhy_tvar", "found");
        hashmap27.put("treti_tvar", "found");
        list.add(hashmap27);
        HashMap hashmap28 = new HashMap();
        hashmap28.put("slovo_cesky", "létat, letět");
        hashmap28.put("prvni_tvar", "fly");
        hashmap28.put("druhy_tvar", "flew");
        hashmap28.put("treti_tvar", "flown");
        list.add(hashmap28);
        HashMap hashmap29 = new HashMap();
        hashmap29.put("slovo_cesky", "zapomenout");
        hashmap29.put("prvni_tvar", "forget");
        hashmap29.put("druhy_tvar", "forgot");
        hashmap29.put("treti_tvar", "forgotten");
        list.add(hashmap29);
        HashMap hashmap30 = new HashMap();
        hashmap30.put("slovo_cesky", "dostat");
        hashmap30.put("prvni_tvar", "get");
        hashmap30.put("druhy_tvar", "got");
        hashmap30.put("treti_tvar", "got, gotten");
        list.add(hashmap30);
        HashMap hashmap31 = new HashMap();
        hashmap31.put("slovo_cesky", "dát, dávat");
        hashmap31.put("prvni_tvar", "give");
        hashmap31.put("druhy_tvar", "gave");
        hashmap31.put("treti_tvar", "given");
        list.add(hashmap31);
        HashMap hashmap32 = new HashMap();
        hashmap32.put("slovo_cesky", "jít, jet");
        hashmap32.put("prvni_tvar", "go");
        hashmap32.put("druhy_tvar", "went");
        hashmap32.put("treti_tvar", "gone");
        list.add(hashmap32);
        HashMap hashmap33 = new HashMap();
        hashmap33.put("slovo_cesky", "růst, vyrůst");
        hashmap33.put("prvni_tvar", "grow");
        hashmap33.put("druhy_tvar", "grew");
        hashmap33.put("treti_tvar", "grown");
        list.add(hashmap33);
        HashMap hashmap34 = new HashMap();
        hashmap34.put("slovo_cesky", "mít");
        hashmap34.put("prvni_tvar", "have");
        hashmap34.put("druhy_tvar", "had");
        hashmap34.put("treti_tvar", "had");
        list.add(hashmap34);
        HashMap hashmap35 = new HashMap();
        hashmap35.put("slovo_cesky", "slyšet");
        hashmap35.put("prvni_tvar", "hear");
        hashmap35.put("druhy_tvar", "heard");
        hashmap35.put("treti_tvar", "heard");
        list.add(hashmap35);
        HashMap hashmap36 = new HashMap();
        hashmap36.put("slovo_cesky", "schovat (se), ukrýt");
        hashmap36.put("prvni_tvar", "hide");
        hashmap36.put("druhy_tvar", "hid");
        hashmap36.put("treti_tvar", "hid, hidden");
        list.add(hashmap36);
        HashMap hashmap37 = new HashMap();
        hashmap37.put("slovo_cesky", "udeřit, trefit");
        hashmap37.put("prvni_tvar", "hit");
        hashmap37.put("druhy_tvar", "hit");
        hashmap37.put("treti_tvar", "hit");
        list.add(hashmap37);
        HashMap hashmap38 = new HashMap();
        hashmap38.put("slovo_cesky", "držet");
        hashmap38.put("prvni_tvar", "hold");
        hashmap38.put("druhy_tvar", "held");
        hashmap38.put("treti_tvar", "held");
        list.add(hashmap38);
        HashMap hashmap39 = new HashMap();
        hashmap39.put("slovo_cesky", "bolet, zranit");
        hashmap39.put("prvni_tvar", "hurt");
        hashmap39.put("druhy_tvar", "hurt");
        hashmap39.put("treti_tvar", "hurt");
        list.add(hashmap39);
        HashMap hashmap40 = new HashMap();
        hashmap40.put("slovo_cesky", "vybrat (si), zvolit (si)");
        hashmap40.put("prvni_tvar", "choose");
        hashmap40.put("druhy_tvar", "chose");
        hashmap40.put("treti_tvar", "chosen");
        list.add(hashmap40);
        HashMap hashmap41 = new HashMap();
        hashmap41.put("slovo_cesky", "nechat, ponechat");
        hashmap41.put("prvni_tvar", "keep");
        hashmap41.put("druhy_tvar", "kept");
        hashmap41.put("treti_tvar", "kept");
        list.add(hashmap41);
        HashMap hashmap42 = new HashMap();
        hashmap42.put("slovo_cesky", "vědět, znát");
        hashmap42.put("prvni_tvar", "know");
        hashmap42.put("druhy_tvar", "knew");
        hashmap42.put("treti_tvar", "known");
        list.add(hashmap42);
        HashMap hashmap43 = new HashMap();
        hashmap43.put("slovo_cesky", "položit");
        hashmap43.put("prvni_tvar", "lay");
        hashmap43.put("druhy_tvar", "laid");
        hashmap43.put("treti_tvar", "laid");
        list.add(hashmap43);
        HashMap hashmap44 = new HashMap();
        hashmap44.put("slovo_cesky", "učit se");
        hashmap44.put("prvni_tvar", "learn");
        hashmap44.put("druhy_tvar", "learned, learnt");
        hashmap44.put("treti_tvar", "learned, learnt");
        list.add(hashmap44);
        HashMap hashmap45 = new HashMap();
        hashmap45.put("slovo_cesky", "odejít, odjet");
        hashmap45.put("prvni_tvar", "leave");
        hashmap45.put("druhy_tvar", "left");
        hashmap45.put("treti_tvar", "left");
        list.add(hashmap45);
        HashMap hashmap46 = new HashMap();
        hashmap46.put("slovo_cesky", "půjčit (něco)");
        hashmap46.put("prvni_tvar", "lend");
        hashmap46.put("druhy_tvar", "lent");
        hashmap46.put("treti_tvar", "lent");
        list.add(hashmap46);
        HashMap hashmap47 = new HashMap();
        hashmap47.put("slovo_cesky", "dovolit, nechat");
        hashmap47.put("prvni_tvar", "let");
        hashmap47.put("druhy_tvar", "let");
        hashmap47.put("treti_tvar", "let");
        list.add(hashmap47);
        HashMap hashmap48 = new HashMap();
        hashmap48.put("slovo_cesky", "ležet");
        hashmap48.put("prvni_tvar", "lie");
        hashmap48.put("druhy_tvar", "lay");
        hashmap48.put("treti_tvar", "lain");
        list.add(hashmap48);
        HashMap hashmap49 = new HashMap();
        hashmap49.put("slovo_cesky", "zapálit");
        hashmap49.put("prvni_tvar", "light");
        hashmap49.put("druhy_tvar", "lighted, lit");
        hashmap49.put("treti_tvar", "lighted, lit");
        list.add(hashmap49);
        HashMap hashmap50 = new HashMap();
        hashmap50.put("slovo_cesky", "ztratit, přijít o");
        hashmap50.put("prvni_tvar", "lose");
        hashmap50.put("druhy_tvar", "lost");
        hashmap50.put("treti_tvar", "lost");
        list.add(hashmap50);
        HashMap hashmap51 = new HashMap();
        hashmap51.put("slovo_cesky", "udělat (vyrobit)");
        hashmap51.put("prvni_tvar", "make");
        hashmap51.put("druhy_tvar", "made");
        hashmap51.put("treti_tvar", "made");
        list.add(hashmap51);
        HashMap hashmap52 = new HashMap();
        hashmap52.put("slovo_cesky", "znamenat");
        hashmap52.put("prvni_tvar", "mean");
        hashmap52.put("druhy_tvar", "meant");
        hashmap52.put("treti_tvar", "meant");
        list.add(hashmap52);
        HashMap hashmap53 = new HashMap();
        hashmap53.put("slovo_cesky", "potkat, setkat se");
        hashmap53.put("prvni_tvar", "meet");
        hashmap53.put("druhy_tvar", "met");
        hashmap53.put("treti_tvar", "met");
        list.add(hashmap53);
        HashMap hashmap54 = new HashMap();
        hashmap54.put("slovo_cesky", "splést (si), poplést (si)");
        hashmap54.put("prvni_tvar", "mistake");
        hashmap54.put("druhy_tvar", "mistook");
        hashmap54.put("treti_tvar", "mistaken");
        list.add(hashmap54);
        HashMap hashmap55 = new HashMap();
        hashmap55.put("slovo_cesky", "platit, zaplatit");
        hashmap55.put("prvni_tvar", "pay");
        hashmap55.put("druhy_tvar", "paid");
        hashmap55.put("treti_tvar", "paid");
        list.add(hashmap55);
        HashMap hashmap56 = new HashMap();
        hashmap56.put("slovo_cesky", "dát (něco někam)");
        hashmap56.put("prvni_tvar", "put");
        hashmap56.put("druhy_tvar", "put");
        hashmap56.put("treti_tvar", "put");
        list.add(hashmap56);
        HashMap hashmap57 = new HashMap();
        hashmap57.put("slovo_cesky", "číst");
        hashmap57.put("prvni_tvar", "read");
        hashmap57.put("druhy_tvar", "read");
        hashmap57.put("treti_tvar", "read");
        list.add(hashmap57);
        HashMap hashmap58 = new HashMap();
        hashmap58.put("slovo_cesky", "jet (na kole, koni..)");
        hashmap58.put("prvni_tvar", "ride");
        hashmap58.put("druhy_tvar", "rode");
        hashmap58.put("treti_tvar", "ridden");
        list.add(hashmap58);
        HashMap hashmap59 = new HashMap();
        hashmap59.put("slovo_cesky", "zvonit, zazvonit");
        hashmap59.put("prvni_tvar", "ring");
        hashmap59.put("druhy_tvar", "rang");
        hashmap59.put("treti_tvar", "rung");
        list.add(hashmap59);
        HashMap hashmap60 = new HashMap();
        hashmap60.put("slovo_cesky", "vstávat, vstát");
        hashmap60.put("prvni_tvar", "rise");
        hashmap60.put("druhy_tvar", "rose");
        hashmap60.put("treti_tvar", "risen");
        list.add(hashmap60);
        HashMap hashmap61 = new HashMap();
        hashmap61.put("slovo_cesky", "běžet, běhat, utíkat");
        hashmap61.put("prvni_tvar", "run");
        hashmap61.put("druhy_tvar", "ran");
        hashmap61.put("treti_tvar", "run");
        list.add(hashmap61);
        HashMap hashmap62 = new HashMap();
        hashmap62.put("slovo_cesky", "říct (něco)");
        hashmap62.put("prvni_tvar", "say");
        hashmap62.put("druhy_tvar", "said");
        hashmap62.put("treti_tvar", "said");
        list.add(hashmap62);
        HashMap hashmap63 = new HashMap();
        hashmap63.put("slovo_cesky", "vidět");
        hashmap63.put("prvni_tvar", "see");
        hashmap63.put("druhy_tvar", "saw");
        hashmap63.put("treti_tvar", "seen");
        list.add(hashmap63);
        HashMap hashmap64 = new HashMap();
        hashmap64.put("slovo_cesky", "prodat, prodávat");
        hashmap64.put("prvni_tvar", "sell");
        hashmap64.put("druhy_tvar", "sold");
        hashmap64.put("treti_tvar", "sold");
        list.add(hashmap64);
        HashMap hashmap65 = new HashMap();
        hashmap65.put("slovo_cesky", "poslat, odeslat");
        hashmap65.put("prvni_tvar", "send");
        hashmap65.put("druhy_tvar", "sent");
        hashmap65.put("treti_tvar", "sent");
        list.add(hashmap65);
        HashMap hashmap66 = new HashMap();
        hashmap66.put("slovo_cesky", "nastavit, nařídit");
        hashmap66.put("prvni_tvar", "set");
        hashmap66.put("druhy_tvar", "set");
        hashmap66.put("treti_tvar", "set");
        list.add(hashmap66);
        HashMap hashmap67 = new HashMap();
        hashmap67.put("slovo_cesky", "střelit, vystřelit");
        hashmap67.put("prvni_tvar", "shoot");
        hashmap67.put("druhy_tvar", "shot");
        hashmap67.put("treti_tvar", "shot");
        list.add(hashmap67);
        HashMap hashmap68 = new HashMap();
        hashmap68.put("slovo_cesky", "ukázat");
        hashmap68.put("prvni_tvar", "show");
        hashmap68.put("druhy_tvar", "showed");
        hashmap68.put("treti_tvar", "shown");
        list.add(hashmap68);
        HashMap hashmap69 = new HashMap();
        hashmap69.put("slovo_cesky", "zavřít, zabouchnout");
        hashmap69.put("prvni_tvar", "shut");
        hashmap69.put("druhy_tvar", "shut");
        hashmap69.put("treti_tvar", "shut");
        list.add(hashmap69);
        HashMap hashmap70 = new HashMap();
        hashmap70.put("slovo_cesky", "zpívat");
        hashmap70.put("prvni_tvar", "sing");
        hashmap70.put("druhy_tvar", "sang");
        hashmap70.put("treti_tvar", "sung");
        list.add(hashmap70);
        HashMap hashmap71 = new HashMap();
        hashmap71.put("slovo_cesky", "sedět");
        hashmap71.put("prvni_tvar", "sit");
        hashmap71.put("druhy_tvar", "sat");
        hashmap71.put("treti_tvar", "sat");
        list.add(hashmap71);
        HashMap hashmap72 = new HashMap();
        hashmap72.put("slovo_cesky", "spát");
        hashmap72.put("prvni_tvar", "sleep");
        hashmap72.put("druhy_tvar", "slept");
        hashmap72.put("treti_tvar", "slept");
        list.add(hashmap72);
        HashMap hashmap73 = new HashMap();
        hashmap73.put("slovo_cesky", "vonět, smrdět, čichat");
        hashmap73.put("prvni_tvar", "smell");
        hashmap73.put("druhy_tvar", "smelled, smelt");
        hashmap73.put("treti_tvar", "smelled, smelt");
        list.add(hashmap73);
        HashMap hashmap74 = new HashMap();
        hashmap74.put("slovo_cesky", "mluvit");
        hashmap74.put("prvni_tvar", "speak");
        hashmap74.put("druhy_tvar", "spoke");
        hashmap74.put("treti_tvar", "spoken");
        list.add(hashmap74);
        HashMap hashmap75 = new HashMap();
        hashmap75.put("slovo_cesky", "hláskovat");
        hashmap75.put("prvni_tvar", "spell");
        hashmap75.put("druhy_tvar", "spelled, splet");
        hashmap75.put("treti_tvar", "spelled, splet");
        list.add(hashmap75);
        HashMap hashmap76 = new HashMap();
        hashmap76.put("slovo_cesky", "utratit (peníze), trávit (čas)");
        hashmap76.put("prvni_tvar", "spend");
        hashmap76.put("druhy_tvar", "spent");
        hashmap76.put("treti_tvar", "spent");
        list.add(hashmap76);
        HashMap hashmap77 = new HashMap();
        hashmap77.put("slovo_cesky", "stát");
        hashmap77.put("prvni_tvar", "stand");
        hashmap77.put("druhy_tvar", "stood");
        hashmap77.put("treti_tvar", "stood");
        list.add(hashmap77);
        HashMap hashmap78 = new HashMap();
        hashmap78.put("slovo_cesky", "krást, ukrást");
        hashmap78.put("prvni_tvar", "steal");
        hashmap78.put("druhy_tvar", "stole");
        hashmap78.put("treti_tvar", "stolen");
        list.add(hashmap78);
        HashMap hashmap79 = new HashMap();
        hashmap79.put("slovo_cesky", "plavat");
        hashmap79.put("prvni_tvar", "swim");
        hashmap79.put("druhy_tvar", "swam");
        hashmap79.put("treti_tvar", "swum");
        list.add(hashmap79);
        HashMap hashmap80 = new HashMap();
        hashmap80.put("slovo_cesky", "vzít (si)");
        hashmap80.put("prvni_tvar", "take");
        hashmap80.put("druhy_tvar", "took");
        hashmap80.put("treti_tvar", "taken");
        list.add(hashmap80);
        HashMap hashmap81 = new HashMap();
        hashmap81.put("slovo_cesky", "učit, vyučovat, naučit");
        hashmap81.put("prvni_tvar", "teach");
        hashmap81.put("druhy_tvar", "taught");
        hashmap81.put("treti_tvar", "taught");
        list.add(hashmap81);
        HashMap hashmap82 = new HashMap();
        hashmap82.put("slovo_cesky", "říci, sdělit");
        hashmap82.put("prvni_tvar", "tell");
        hashmap82.put("druhy_tvar", "told");
        hashmap82.put("treti_tvar", "told");
        list.add(hashmap82);
        HashMap hashmap83 = new HashMap();
        hashmap83.put("slovo_cesky", "myslet (si), přemýšlet");
        hashmap83.put("prvni_tvar", "think");
        hashmap83.put("druhy_tvar", "thought");
        hashmap83.put("treti_tvar", "thought");
        list.add(hashmap83);
        HashMap hashmap84 = new HashMap();
        hashmap84.put("slovo_cesky", "házet, hodit");
        hashmap84.put("prvni_tvar", "throw");
        hashmap84.put("druhy_tvar", "threw");
        hashmap84.put("treti_tvar", "thrown");
        list.add(hashmap84);
        HashMap hashmap85 = new HashMap();
        hashmap85.put("slovo_cesky", "rozumět");
        hashmap85.put("prvni_tvar", "understand");
        hashmap85.put("druhy_tvar", "understood");
        hashmap85.put("treti_tvar", "understood");
        list.add(hashmap85);
        HashMap hashmap86 = new HashMap();
        hashmap86.put("slovo_cesky", "probudit, vzbudit");
        hashmap86.put("prvni_tvar", "wake");
        hashmap86.put("druhy_tvar", "woke");
        hashmap86.put("treti_tvar", "woken");
        list.add(hashmap86);
        HashMap hashmap87 = new HashMap();
        hashmap87.put("slovo_cesky", "nosit, mít na sobě");
        hashmap87.put("prvni_tvar", "wear");
        hashmap87.put("druhy_tvar", "wore");
        hashmap87.put("treti_tvar", "worn");
        list.add(hashmap87);
        HashMap hashmap88 = new HashMap();
        hashmap88.put("slovo_cesky", "psát, napsat");
        hashmap88.put("prvni_tvar", "write");
        hashmap88.put("druhy_tvar", "wrote");
        hashmap88.put("treti_tvar", "written");
        list.add(hashmap88);
        this.listView.setAdapter(new SimpleAdapter(this, list, R.layout.custom_filter, new String[]{"slovo_cesky", "prvni_tvar", "druhy_tvar", "treti_tvar"}, new int[]{R.id.textView9, R.id.textView18, R.id.textView20, R.id.textView19}));
    }
}
